export const environment = {
    production: false,
    sso: {
        clientId: 'vA_wiC5UC304HmXyvP9_HP09Mb4a',
        serverUrl: 'https://infra-apim.virtus-way.org',
        issuer: '/oauth2/token',
        redirectUri: 'https://infra-business.virtus-way.org',
        scope: 'openid profile',
        tokenEndpoint: '/oauth2/token',
        userinfoEndpoint: '/oauth2/userinfo',
        loginEndpoint: '/oauth2/authorize',
        logoutEndpoint: '/oidc/logout',
        jwksEndpoint: '/oauth2/jwks',
        showDebugInformation: true,
        requireHttps: false,
        responseType: 'id_token token'
    },
    wso2: {
        businessApikey: 'eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ2aXJ0dXNAY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJ2aXJ0dXMiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkJ1c2luZXNzLUFwcGxpY2F0aW9uIiwiaWQiOjMsInV1aWQiOiIwMDQ0NTNkZC02OTY5LTQxZWUtOTNkZC0wYTYwN2JmYjM5YzEifSwiaXNzIjoiaHR0cHM6XC9cL2luZnJhLWFwaW0udmlydHVzLXdheS5vcmc6NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiVW5saW1pdGVkIjp7InRpZXJRdW90YVR5cGUiOiJyZXF1ZXN0Q291bnQiLCJncmFwaFFMTWF4Q29tcGxleGl0eSI6MCwiZ3JhcGhRTE1heERlcHRoIjowLCJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJwZXJtaXR0ZWRSZWZlcmVyIjoiIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoid2F5LWJ1c2luZXNzIiwiY29udGV4dCI6IlwvYnVzaW5lc3NcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwicGVybWl0dGVkSVAiOiIiLCJpYXQiOjE2MzQxNDYxNTAsImp0aSI6IjliY2EyMTNmLTk2OTctNGZhZS05M2MwLThlY2FmZDQ4MjU3OCJ9.YUb-UdGLaA2lT5MzCSsIKcGaGaCqbtYvp0SR5QP1pMByXnlhPmW5HvZHK40qr_DECdB9xUox3Pc4VZjFNJ824bHzpZODhKLSRsiXikbWC4yeKSmig91ng3sg9IVXrm3Woy4CgTAvN9i21oHXYETb_tuEVzqb38SnbMM7_mBjlhhbhbJbdbk-X1ZLEBnDXb5pcmg1SQddVXMWS8AUNy5zm5B33QY1593RvxwHVgeKjk3IHxDMe6vLinIwfUa6BZTPnxTWSdVXqPXMEO8Fk8OjpttsPNqZjwL5sDfThcxMzJzha2Pw-NMvJ3qDyMC9QQxDaEwZIQTsrmuBf9w33v4lpQ==',
        coreApikey: 'eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ2aXJ0dXNAY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJ2aXJ0dXMiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkNvcmUtQXBwbGljYXRpb24iLCJpZCI6MiwidXVpZCI6ImM4N2U0ZGFjLWQ5ODItNDYyNi1hNWY0LWJjYWVjNGE1MTk4ZSJ9LCJpc3MiOiJodHRwczpcL1wvaW5mcmEtYXBpbS52aXJ0dXMtd2F5Lm9yZzo0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInBlcm1pdHRlZFJlZmVyZXIiOiIiLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktY29yZSIsImNvbnRleHQiOiJcL2NvcmVcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktdHJhY2tlciIsImNvbnRleHQiOiJcL3RyYWNrZXJcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktYnVzaW5lc3MiLCJjb250ZXh0IjoiXC9idXNpbmVzc1wvdjEiLCJwdWJsaXNoZXIiOiJ2aXJ0dXMiLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJwZXJtaXR0ZWRJUCI6IiIsImlhdCI6MTYzNDE0NjEwNiwianRpIjoiMWVmMTU4ZDMtMTliYS00MTZmLTkwNzUtNDdkZWUxMTMwMGFjIn0=.caeyvJM2kxvbJc951ftKbq3PipAKDwU4Tt7TDZtSx5B4ZYIQm5cnM_owZ4scBm7WIveLoiF_z4xHUVcN4teO29pPfqZNW5KbfOBRgzSMy_uB1Y8xpB_fOcE9iEnNCZf13pHi_SIADBXO0Mx1htRE4lJXffW8H9S15_H_8_lk-D4dcay00lNIAw5JKr5pD8sbVy_GF3HccM0r-Z0nCshAnO5H0XpwTXNhsjfll4zIEqXdEz58iA0VX9VhAGXUL7MmFaEeeyRVFvq0eAznFYOYtBiYwHnOf0yZDuzFq2bDrBjTCPBSpswbEVgYBPGRrz0_sgHISclANSw3RoW637fzDQ=='
    },
    portalAppLink: 'https://infra.virtus-way.org',
    moduleId: 2,
    url: 'https://infra-apim.virtus-way.org/gateway/'
};
