version: 0.2

env:
  exported-variables:
    - MODULE
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - rm -rf ./client/${MODULE}/node_modules/common
      - rm -rf ./client/${MODULE}/package-lock.json

      # reading module's tracker when available
      - |
        if [ -n "${TRACKER_URL}" ] && [ -n "${TRACKER_SCRIPT}" ];
        then
          TRACKER_URL_ESC=$(echo "${TRACKER_URL}" | sed -r "s/[\*\.\/\&\:]/\\\\&/g")
          sed -r -i "s/http\:\/\/localhost\:4203/${TRACKER_URL_ESC}/g" ./client/${MODULE}/src/assets/import-map.json
          TRACKER_SCRIPT_ESC=$(echo "${TRACKER_SCRIPT}" | sed "s/[\*\.\/\&\:]/\\\\&/g")
          sed -r -i "s/main.js/${TRACKER_SCRIPT_ESC}/g" ./client/${MODULE}/src/assets/import-map.json
        fi
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      
      - echo '##############################' Building client:${MODULE}
      - npm --prefix ./client/${MODULE} install
      - npm --prefix ./client/${MODULE} run build:${BUILD_ENV}
artifacts:
  files:
    - './client/${MODULE}/dist/${MODULE}/**/*'
    - './buildspec.client-deploy.yml'
cache:
  paths:
    - '/root/.npm/**/*'
    - './client/${MODULE}/node_modules/**/*'