package br.edu.ufcg.virtus.tracker.dto;

import java.util.Calendar;

import br.edu.ufcg.virtus.common.dto.ModelDTO;
import br.edu.ufcg.virtus.tracker.dto.search.TrackerSearchDTO;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CommentDTO extends ModelDTO {

    private Integer id;
    private String text;
    private String user;
    private String username;
    private Calendar createdOn;
    private TrackerSearchDTO tracker;
    private boolean autoGenerated;
    private boolean systemLog;

}
