-- Create root user
CREATE ROLE IF NOT EXISTS virtus WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'master';

-- Create database
CREATE DATABASE IF NOT EXISTS "virtus_way" WITH OWNER "virtus" ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE template0;


-- Create scheme core;
CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION virtus;