server:
  port: 8083
  url: "https://infra-apim.virtus-way.org/gateway/"
spring:
  application:
    name: tracker
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    dispatch-options-request: true
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob: 
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://infra-way-db.cecmaagdmtj5.us-east-2.rds.amazonaws.com:5432/virtus_way?currentSchema=tracker
    username: virtus
    password: Virtu$w4y
    dbcp2:
      initial-size: 5
      max-total: 40
      pool-prepared-statements: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: tracker
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: virtus-way@outlook.com
    password: 'Virtu$w4y'
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
          ssl: 
            trust: smtp.office365.com
        transport: 
          protocol: smt
jwt:
  config:
    type: encrypted
wso2:
    core-api-key: "eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ2aXJ0dXNAY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJ2aXJ0dXMiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkNvcmUtQXBwbGljYXRpb24iLCJpZCI6MiwidXVpZCI6ImM4N2U0ZGFjLWQ5ODItNDYyNi1hNWY0LWJjYWVjNGE1MTk4ZSJ9LCJpc3MiOiJodHRwczpcL1wvaW5mcmEtYXBpbS52aXJ0dXMtd2F5Lm9yZzo0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInBlcm1pdHRlZFJlZmVyZXIiOiIiLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktY29yZSIsImNvbnRleHQiOiJcL2NvcmVcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktdHJhY2tlciIsImNvbnRleHQiOiJcL3RyYWNrZXJcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktYnVzaW5lc3MiLCJjb250ZXh0IjoiXC9idXNpbmVzc1wvdjEiLCJwdWJsaXNoZXIiOiJ2aXJ0dXMiLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJwZXJtaXR0ZWRJUCI6IiIsImlhdCI6MTYzNDE0NjEwNiwianRpIjoiMWVmMTU4ZDMtMTliYS00MTZmLTkwNzUtNDdkZWUxMTMwMGFjIn0=.caeyvJM2kxvbJc951ftKbq3PipAKDwU4Tt7TDZtSx5B4ZYIQm5cnM_owZ4scBm7WIveLoiF_z4xHUVcN4teO29pPfqZNW5KbfOBRgzSMy_uB1Y8xpB_fOcE9iEnNCZf13pHi_SIADBXO0Mx1htRE4lJXffW8H9S15_H_8_lk-D4dcay00lNIAw5JKr5pD8sbVy_GF3HccM0r-Z0nCshAnO5H0XpwTXNhsjfll4zIEqXdEz58iA0VX9VhAGXUL7MmFaEeeyRVFvq0eAznFYOYtBiYwHnOf0yZDuzFq2bDrBjTCPBSpswbEVgYBPGRrz0_sgHISclANSw3RoW637fzDQ=="
aws:
  bucket: virtus-way-files/infra
 