DO $$
BEGIN
  CREATE ROLE virtus WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'master';
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'not creating role virtus -- it already exists';
END
$$;

SELECT 'CREATE DATABASE virtus_way WITH OWNER virtus ENCODING "UTF8" LC_COLLATE = "en_US.UTF-8" LC_CTYPE = "en_US.UTF-8" TEMPLATE template0'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'virtus_way')\gexec

GRANT CONNECT ON DATABASE virtus_way TO virtus;
CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION virtus;
CREATE SCHEMA IF NOT EXISTS business AUTHORIZATION virtus;
