server:
  port: 8082
  url: "https://demo-apim.virtus-way.org/gateway/"
spring:
  application:
    name: business
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    dispatch-options-request: true
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob: 
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://homolog-way-db.cecmaagdmtj5.us-east-2.rds.amazonaws.com:5432/virtus_way?currentSchema=business
    username: virtus
    password: Virtu$w4y
    dbcp2:
      initial-size: 5
      max-total: 40
      pool-prepared-statements: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: business
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: virtus-way@outlook.com
    password: 'Virtu$w4y'
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
          ssl: 
            trust: smtp.office365.com
        transport: 
          protocol: smt
jwt:
  config:
    type: encrypted
wso2:
    core-api-key: "eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ2aXJ0dXNAY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJ2aXJ0dXMiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkNvcmUtQXBwbGljYXRpb24iLCJpZCI6NSwidXVpZCI6IjJiNjRlYjI5LTQwNDUtNGFkNC04NDgwLWQ1ZmZmZjgzNzgwNCJ9LCJpc3MiOiJodHRwczpcL1wvZGVtby1hcGltLnZpcnR1cy13YXkub3JnOjQ0M1wvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7IlVubGltaXRlZCI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwicGVybWl0dGVkUmVmZXJlciI6IiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IndheS1jb3JlIiwiY29udGV4dCI6IlwvY29yZVwvdjEiLCJwdWJsaXNoZXIiOiJFWFRFUk5BTFwvaHlnZ28iLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn0seyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IndheS1idXNpbmVzcyIsImNvbnRleHQiOiJcL2J1c2luZXNzXC92MSIsInB1Ymxpc2hlciI6InZpcnR1cyIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoid2F5LXRyYWNrZXIiLCJjb250ZXh0IjoiXC90cmFja2VyXC92MSIsInB1Ymxpc2hlciI6IkVYVEVSTkFMXC9oeWdnbyIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifV0sInBlcm1pdHRlZElQIjoiIiwiaWF0IjoxNjM2NzQ1MTYwLCJqdGkiOiJjYWUwMTk2ZC01ZWEwLTQ0NWUtODA5OC1jMDM1Yjk5YjVjMmQifQ==.FFnmBVgDmJrjMbMQaPAilt4WQjBvsE7HY0klF0g0bdDku21WRO9JtKcRX18-W6tqUzJ-A12nw5okngF3DzVheh2HJ6qdVYSrFn0QmbbUwOHinyYuP0dUT8FuERi87bjhRObnvLggdjNxYjKzBuPknEo99x-Mn4Rnn8z9k7YgtU-vS92ar_oKPBzFv75sNMgoQ7YNn4jnYqj5wS8CSWS_wlxLuh-_sNeBvRtsN59tj9c81lMx9u-R8gl1Envs7tkwURgdcxUDKan8gmx0NBnouA_NIaMLE3v2gYXxzc6-_zSow8j9F28mMRpMbC44y1A2H2wjWKXaUBH0RRWDHXVpXA=="
